//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MedicalModel", "FK_Atz_Brr_Atz_Mun", "Cad_Mun", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(br.com.totaltiss.Data.Cad_Mun), "Cad_Brr", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(br.com.totaltiss.Data.Cad_Brr), true)]

#endregion

namespace br.com.totaltiss.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MedicallEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MedicallEntities object using the connection string found in the 'MedicallEntities' section of the application configuration file.
        /// </summary>
        public MedicallEntities() : base("name=MedicallEntities", "MedicallEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MedicallEntities object.
        /// </summary>
        public MedicallEntities(string connectionString) : base(connectionString, "MedicallEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MedicallEntities object.
        /// </summary>
        public MedicallEntities(EntityConnection connection) : base(connection, "MedicallEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cad_Esp> Cad_Esp
        {
            get
            {
                if ((_Cad_Esp == null))
                {
                    _Cad_Esp = base.CreateObjectSet<Cad_Esp>("Cad_Esp");
                }
                return _Cad_Esp;
            }
        }
        private ObjectSet<Cad_Esp> _Cad_Esp;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cad_Brr> Cad_Brr
        {
            get
            {
                if ((_Cad_Brr == null))
                {
                    _Cad_Brr = base.CreateObjectSet<Cad_Brr>("Cad_Brr");
                }
                return _Cad_Brr;
            }
        }
        private ObjectSet<Cad_Brr> _Cad_Brr;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cad_Mun> Cad_Mun
        {
            get
            {
                if ((_Cad_Mun == null))
                {
                    _Cad_Mun = base.CreateObjectSet<Cad_Mun>("Cad_Mun");
                }
                return _Cad_Mun;
            }
        }
        private ObjectSet<Cad_Mun> _Cad_Mun;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ans_Tpl> Ans_Tpl
        {
            get
            {
                if ((_Ans_Tpl == null))
                {
                    _Ans_Tpl = base.CreateObjectSet<Ans_Tpl>("Ans_Tpl");
                }
                return _Ans_Tpl;
            }
        }
        private ObjectSet<Ans_Tpl> _Ans_Tpl;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cad_Esp EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCad_Esp(Cad_Esp cad_Esp)
        {
            base.AddObject("Cad_Esp", cad_Esp);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cad_Brr EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCad_Brr(Cad_Brr cad_Brr)
        {
            base.AddObject("Cad_Brr", cad_Brr);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cad_Mun EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCad_Mun(Cad_Mun cad_Mun)
        {
            base.AddObject("Cad_Mun", cad_Mun);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ans_Tpl EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAns_Tpl(Ans_Tpl ans_Tpl)
        {
            base.AddObject("Ans_Tpl", ans_Tpl);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MedicalModel", Name="Ans_Tpl")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ans_Tpl : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ans_Tpl object.
        /// </summary>
        /// <param name="idTpl">Initial value of the IdTpl property.</param>
        /// <param name="tpl_Dsc">Initial value of the Tpl_Dsc property.</param>
        public static Ans_Tpl CreateAns_Tpl(global::System.Int16 idTpl, global::System.String tpl_Dsc)
        {
            Ans_Tpl ans_Tpl = new Ans_Tpl();
            ans_Tpl.IdTpl = idTpl;
            ans_Tpl.Tpl_Dsc = tpl_Dsc;
            return ans_Tpl;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 IdTpl
        {
            get
            {
                return _IdTpl;
            }
            set
            {
                if (_IdTpl != value)
                {
                    OnIdTplChanging(value);
                    ReportPropertyChanging("IdTpl");
                    _IdTpl = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdTpl");
                    OnIdTplChanged();
                }
            }
        }
        private global::System.Int16 _IdTpl;
        partial void OnIdTplChanging(global::System.Int16 value);
        partial void OnIdTplChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tpl_Dsc
        {
            get
            {
                return _Tpl_Dsc;
            }
            set
            {
                OnTpl_DscChanging(value);
                ReportPropertyChanging("Tpl_Dsc");
                _Tpl_Dsc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tpl_Dsc");
                OnTpl_DscChanged();
            }
        }
        private global::System.String _Tpl_Dsc;
        partial void OnTpl_DscChanging(global::System.String value);
        partial void OnTpl_DscChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MedicalModel", Name="Cad_Brr")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cad_Brr : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cad_Brr object.
        /// </summary>
        /// <param name="idBrr">Initial value of the IdBrr property.</param>
        /// <param name="brr_IdMun">Initial value of the Brr_IdMun property.</param>
        /// <param name="brr_Nme">Initial value of the Brr_Nme property.</param>
        public static Cad_Brr CreateCad_Brr(global::System.Int32 idBrr, global::System.Int16 brr_IdMun, global::System.String brr_Nme)
        {
            Cad_Brr cad_Brr = new Cad_Brr();
            cad_Brr.IdBrr = idBrr;
            cad_Brr.Brr_IdMun = brr_IdMun;
            cad_Brr.Brr_Nme = brr_Nme;
            return cad_Brr;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdBrr
        {
            get
            {
                return _IdBrr;
            }
            set
            {
                if (_IdBrr != value)
                {
                    OnIdBrrChanging(value);
                    ReportPropertyChanging("IdBrr");
                    _IdBrr = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdBrr");
                    OnIdBrrChanged();
                }
            }
        }
        private global::System.Int32 _IdBrr;
        partial void OnIdBrrChanging(global::System.Int32 value);
        partial void OnIdBrrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Brr_IdMun
        {
            get
            {
                return _Brr_IdMun;
            }
            set
            {
                OnBrr_IdMunChanging(value);
                ReportPropertyChanging("Brr_IdMun");
                _Brr_IdMun = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Brr_IdMun");
                OnBrr_IdMunChanged();
            }
        }
        private global::System.Int16 _Brr_IdMun;
        partial void OnBrr_IdMunChanging(global::System.Int16 value);
        partial void OnBrr_IdMunChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Brr_Nme
        {
            get
            {
                return _Brr_Nme;
            }
            set
            {
                OnBrr_NmeChanging(value);
                ReportPropertyChanging("Brr_Nme");
                _Brr_Nme = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Brr_Nme");
                OnBrr_NmeChanged();
            }
        }
        private global::System.String _Brr_Nme;
        partial void OnBrr_NmeChanging(global::System.String value);
        partial void OnBrr_NmeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MedicalModel", "FK_Atz_Brr_Atz_Mun", "Cad_Mun")]
        public Cad_Mun Cad_Mun
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cad_Mun>("MedicalModel.FK_Atz_Brr_Atz_Mun", "Cad_Mun").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cad_Mun>("MedicalModel.FK_Atz_Brr_Atz_Mun", "Cad_Mun").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cad_Mun> Cad_MunReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cad_Mun>("MedicalModel.FK_Atz_Brr_Atz_Mun", "Cad_Mun");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cad_Mun>("MedicalModel.FK_Atz_Brr_Atz_Mun", "Cad_Mun", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MedicalModel", Name="Cad_Esp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cad_Esp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cad_Esp object.
        /// </summary>
        /// <param name="idEsp">Initial value of the IdEsp property.</param>
        /// <param name="esp_Dsc">Initial value of the Esp_Dsc property.</param>
        public static Cad_Esp CreateCad_Esp(global::System.Int16 idEsp, global::System.String esp_Dsc)
        {
            Cad_Esp cad_Esp = new Cad_Esp();
            cad_Esp.IdEsp = idEsp;
            cad_Esp.Esp_Dsc = esp_Dsc;
            return cad_Esp;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 IdEsp
        {
            get
            {
                return _IdEsp;
            }
            set
            {
                if (_IdEsp != value)
                {
                    OnIdEspChanging(value);
                    ReportPropertyChanging("IdEsp");
                    _IdEsp = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdEsp");
                    OnIdEspChanged();
                }
            }
        }
        private global::System.Int16 _IdEsp;
        partial void OnIdEspChanging(global::System.Int16 value);
        partial void OnIdEspChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Esp_Dsc
        {
            get
            {
                return _Esp_Dsc;
            }
            set
            {
                OnEsp_DscChanging(value);
                ReportPropertyChanging("Esp_Dsc");
                _Esp_Dsc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Esp_Dsc");
                OnEsp_DscChanged();
            }
        }
        private global::System.String _Esp_Dsc;
        partial void OnEsp_DscChanging(global::System.String value);
        partial void OnEsp_DscChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Esp_Cbo
        {
            get
            {
                return _Esp_Cbo;
            }
            set
            {
                OnEsp_CboChanging(value);
                ReportPropertyChanging("Esp_Cbo");
                _Esp_Cbo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Esp_Cbo");
                OnEsp_CboChanged();
            }
        }
        private global::System.String _Esp_Cbo;
        partial void OnEsp_CboChanging(global::System.String value);
        partial void OnEsp_CboChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MedicalModel", Name="Cad_Mun")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cad_Mun : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cad_Mun object.
        /// </summary>
        /// <param name="idMun">Initial value of the IdMun property.</param>
        /// <param name="mun_Cod">Initial value of the Mun_Cod property.</param>
        /// <param name="mun_Nme">Initial value of the Mun_Nme property.</param>
        /// <param name="mun_Est">Initial value of the Mun_Est property.</param>
        public static Cad_Mun CreateCad_Mun(global::System.Int16 idMun, global::System.String mun_Cod, global::System.String mun_Nme, global::System.String mun_Est)
        {
            Cad_Mun cad_Mun = new Cad_Mun();
            cad_Mun.IdMun = idMun;
            cad_Mun.Mun_Cod = mun_Cod;
            cad_Mun.Mun_Nme = mun_Nme;
            cad_Mun.Mun_Est = mun_Est;
            return cad_Mun;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 IdMun
        {
            get
            {
                return _IdMun;
            }
            set
            {
                if (_IdMun != value)
                {
                    OnIdMunChanging(value);
                    ReportPropertyChanging("IdMun");
                    _IdMun = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdMun");
                    OnIdMunChanged();
                }
            }
        }
        private global::System.Int16 _IdMun;
        partial void OnIdMunChanging(global::System.Int16 value);
        partial void OnIdMunChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Mun_Cod
        {
            get
            {
                return _Mun_Cod;
            }
            set
            {
                OnMun_CodChanging(value);
                ReportPropertyChanging("Mun_Cod");
                _Mun_Cod = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Mun_Cod");
                OnMun_CodChanged();
            }
        }
        private global::System.String _Mun_Cod;
        partial void OnMun_CodChanging(global::System.String value);
        partial void OnMun_CodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Mun_Nme
        {
            get
            {
                return _Mun_Nme;
            }
            set
            {
                OnMun_NmeChanging(value);
                ReportPropertyChanging("Mun_Nme");
                _Mun_Nme = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Mun_Nme");
                OnMun_NmeChanged();
            }
        }
        private global::System.String _Mun_Nme;
        partial void OnMun_NmeChanging(global::System.String value);
        partial void OnMun_NmeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Mun_Est
        {
            get
            {
                return _Mun_Est;
            }
            set
            {
                OnMun_EstChanging(value);
                ReportPropertyChanging("Mun_Est");
                _Mun_Est = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Mun_Est");
                OnMun_EstChanged();
            }
        }
        private global::System.String _Mun_Est;
        partial void OnMun_EstChanging(global::System.String value);
        partial void OnMun_EstChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MedicalModel", "FK_Atz_Brr_Atz_Mun", "Cad_Brr")]
        public EntityCollection<Cad_Brr> Cad_Brr
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cad_Brr>("MedicalModel.FK_Atz_Brr_Atz_Mun", "Cad_Brr");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cad_Brr>("MedicalModel.FK_Atz_Brr_Atz_Mun", "Cad_Brr", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
